<a href="https://colab.research.google.com/github/maithoi/Cracking-Kaggle/blob/master/10_Days_of_Statistics_HACKERANK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Find Mode 


## If all elemennts have equal occurrence then get element with maximum value as MODE


In [0]:
import statistics
def find_max_mode(list1):
    list_table = statistics._counts(list1)
    len_table = len(list_table)

    if len_table == 1:
        max_mode = statistics.mode(list1)
    else:
        new_list = []
        for i in range(len_table):
            new_list.append(list_table[i][0])
        max_mode = max(new_list) # use the max value here
    return max_mode

if __name__ == '__main__':
    a = [1,1,2,2,3,3, 5,5]
    print(find_max_mode(a)) # print 2

5


In [0]:

# count the occurrence of list of numbers.
list_table = statistics._counts(a)
print(type(list_table))
list_table

<class 'list'>


[(1, 2), (2, 2), (3, 2), (5, 2)]

In [0]:
b = [1,1,2,2,3,3, 5,5, 5]
list_table = statistics._counts(b)
list_table

[(5, 3)]

# Calculate Softmax Function


In [39]:
import numpy as np 
test1 = [4.1, 3.2, 1.9, 1.6, 1.5, 2.9]
# test2 = [2.0, 3.9, 2.6, 1.7, 1.5, 3.2]
# test3 = [3.5, 4.1, 1.6, 3.7, 1.5, 2.2]
# test4 = [0.8, 1.1, 2.6, 2.5, 1.5, 0.9]
# test5 = [2.5, 3.1, 2.7, 1.7, 2.4, 3.4]
# test6 = [3.5, 3.1, 2.9, 1.7, 1.5, 3.4]

exps = [np.exp(i) for i in test1]
print(exps)

sum_exps = np.sum(exps)
print(sum_exps)

softmax = [i/sum_exps for i in exps]
print("softmax", softmax)

# TODO 
# Test2 
# Test3 
# Test4
# Test5 
# Test6





[60.34028759736195, 24.532530197109352, 6.6858944422792685, 4.953032424395115, 4.4816890703380645, 18.17414536944306]
119.16757910092682
softmax [0.50634818675185, 0.2058658099979691, 0.05610497832314586, 0.041563590212739275, 0.03760829165239968, 0.15250914306189603]


In [49]:
import numpy as np
test_input = test1 = [
                        [4.1, 3.2, 1.9, 1.6, 1.5, 2.9],
                        [2.0, 3.9, 2.6, 1.7, 1.5, 3.2],
                        [3.5, 4.1, 1.6, 3.7, 1.5, 2.2],
                        [0.8, 1.1, 2.6, 2.5, 1.5, 0.9],
                        [2.5, 3.1, 2.7, 1.7, 2.4, 3.4],
                        [3.5, 3.1, 2.9, 1.7, 1.5, 3.4]]


test_arr = np.asarray(test_input)
print(type(test_arr))


exps = [np.exp(i) for i in test_arr]
print(exps_arr)

sum_of_exps = [np.sum(i) for i in exps]
print(sum_arr)

print('*' * 100)

exps_arr = np.array(exps)
sum_arr = np.array(sum_of_exps)

# Divide elements at the same index --> arr1[i]/ arr2[i]

softmax = exps_arr / sum_arr[:, None]

print(softmax)


<class 'numpy.ndarray'>
[[60.3402876  24.5325302   6.68589444  4.95303242  4.48168907 18.17414537]
 [ 7.3890561  49.40244911 13.46373804  5.47394739  4.48168907 24.5325302 ]
 [33.11545196 60.3402876   4.95303242 40.44730436  4.48168907  9.0250135 ]
 [ 2.22554093  3.00416602 13.46373804 12.18249396  4.48168907  2.45960311]
 [12.18249396 22.19795128 14.87973172  5.47394739 11.02317638 29.96410005]
 [33.11545196 22.19795128 18.17414537  5.47394739  4.48168907 29.96410005]]
[119.1675791  104.7434099  152.36277891  37.81723113  95.72140079
 113.40728512]
****************************************************************************************************
[[0.50634819 0.20586581 0.05610498 0.04156359 0.03760829 0.15250914]
 [0.07054435 0.4716521  0.12854019 0.05226054 0.04278731 0.2342155 ]
 [0.21734607 0.39603037 0.03250815 0.2654671  0.02941459 0.05923372]
 [0.05884992 0.07943908 0.35602125 0.32214135 0.11850918 0.06503922]
 [0.12727033 0.23190166 0.15544833 0.05718624 0.11515895 0.31303449


[EVALUATE & CALCULATE__Top-N__Accuracy & Error](https://stackoverflow.com/questions/37668902/evaluation-calculate-top-n-accuracy-top-1-and-top-5)

## Top-1 Accurracy & Top-5 Accurracy

Top-1 accuracy is the conventional accuracy: the model answer (the one with highest probability) must be exactly the expected answer.

Top-5 accuracy means that any of your model 5 highest probability answers must match the expected answer.

For instance, let's say you're applying machine learning to object recognition using a neural network. A picture of a cat is shown, and these are the outputs of your neural network:

1. Tiger: 0.4
2. Dog: 0.3
3. Cat: 0.1
4. Lynx: 0.09
5. Lion: 0.08
6. Bird: 0.02
7. Bear: 0.01









Using top-1 accuracy, you count this output as wrong, because it predicted a tiger.

Using top-5 accuracy, you count this output as correct, because cat is among the top-5 guesses.


## Top-1 Error & Top-5 Error

The Complement of the accuracy is the error, The top-1 error is the percentage of time that the classifier did not give the correct class highest probability score. The top-5 error:- The percentage of time that the classifier did not include the correct class among the top 5 probabilities or guesses.